/**
 * Config Template Generator
 *
 * Generates a config.ts file for a new use case following the patterns
 * established in simple-translator and subworkflow-demo.
 */

export interface ConfigTemplateParams {
  name: string;
  slug: string;
  description: string;
  icon: string;
  withDataIngestion?: boolean;
}

/**
 * Generate a complete config.ts file as a string.
 */
export function generateConfigTs(params: ConfigTemplateParams): string {
  const { name, slug, description, icon, withDataIngestion } = params;

  const dataIngestionImport = withDataIngestion
    ? `\n  type ProcessDataIngestionConfigInput,`
    : '';

  return `/**
 * ${name} - Configuration
 *
 * Generated by codika-helper init.
 * Edit this file to customize your use case deployment configuration.
 */

import { dirname, join } from 'path';
import { fileURLToPath } from 'url';
import {
  loadAndEncodeWorkflow,
  type FormInputSchema,
  type FormOutputSchema,
  type HttpTrigger,
  type ScheduleTrigger,
  type SubworkflowTrigger,
  type ProcessDeploymentConfigurationInput,${dataIngestionImport}
} from '@codika-io/helper-sdk';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

/**
 * List of workflow files for archiving and metadata
 */
export const WORKFLOW_FILES = [
  join(__dirname, 'workflows/main-workflow.json'),
  join(__dirname, 'workflows/scheduled-report.json'),
  join(__dirname, 'workflows/text-processor.json'),
];

/**
 * Get the complete deployment configuration for this use case
 */
export function getConfiguration(): ProcessDeploymentConfigurationInput {
  const httpTriggerId = crypto.randomUUID();
  const scheduleTriggerId = crypto.randomUUID();
  const subworkflowTriggerId = crypto.randomUUID();

  // URL patterns with placeholders
  const webhookUrl = \`{{ORGSECRET_N8N_BASE_URL_TERCESORG}}/webhook/{{PROCDATA_PROCESS_ID_ATADCORP}}/{{USERDATA_PROCESS_INSTANCE_UID_ATADRESU}}/${slug}\`;
  const manualTriggerUrl = \`{{ORGSECRET_N8N_BASE_URL_TERCESORG}}/webhook/{{PROCDATA_PROCESS_ID_ATADCORP}}/{{USERDATA_PROCESS_INSTANCE_UID_ATADRESU}}/${slug}-report\`;

  // Load and encode workflows
  const mainWorkflowBase64 = loadAndEncodeWorkflow(
    join(__dirname, 'workflows/main-workflow.json')
  );
  const scheduledReportBase64 = loadAndEncodeWorkflow(
    join(__dirname, 'workflows/scheduled-report.json')
  );
  const textProcessorBase64 = loadAndEncodeWorkflow(
    join(__dirname, 'workflows/text-processor.json')
  );

  const workflows = [
    // Main workflow - user-facing HTTP trigger
    {
      workflowTemplateId: 'main-workflow',
      workflowId: 'main-workflow',
      workflowName: 'Main Workflow',
      markdownInfo: getMainWorkflowMarkdown(),
      knowledgeBaseAccess: {
        processDocTags: [],
        processInstanceDocTags: [],
      },
      integrationUids: [] as string[],
      triggers: [
        {
          triggerId: httpTriggerId,
          type: 'http' as const,
          url: webhookUrl,
          method: 'POST' as const,
          title: 'Process Text',
          description: 'Submit text to be processed',
          inputSchema: getInputSchema(),
        } satisfies HttpTrigger,
      ],
      outputSchema: getOutputSchema(),
      n8nWorkflowJsonBase64: mainWorkflowBase64,
      cost: 1,
    },
    // Scheduled report workflow
    {
      workflowTemplateId: 'scheduled-report',
      workflowId: 'scheduled-report',
      workflowName: 'Scheduled Report',
      markdownInfo: getScheduledReportMarkdown(),
      knowledgeBaseAccess: {
        processDocTags: [],
        processInstanceDocTags: [],
      },
      integrationUids: [] as string[],
      triggers: [
        {
          triggerId: scheduleTriggerId,
          type: 'schedule' as const,
          cronExpression: '0 9 * * 1',
          timezone: 'Europe/Amsterdam',
          humanReadable: 'Every Monday at 9:00 AM',
          manualTriggerUrl: manualTriggerUrl,
          title: 'Weekly Report',
          description: 'Generates a report every Monday at 9 AM',
        } satisfies ScheduleTrigger,
      ],
      outputSchema: getReportOutputSchema(),
      n8nWorkflowJsonBase64: scheduledReportBase64,
      cost: 1,
    },
    // Text processor sub-workflow (called by main workflow)
    {
      workflowTemplateId: 'text-processor',
      workflowId: 'text-processor',
      workflowName: 'Text Processor',
      markdownInfo: getTextProcessorMarkdown(),
      knowledgeBaseAccess: {
        processDocTags: [],
        processInstanceDocTags: [],
      },
      integrationUids: [] as string[],
      triggers: [
        {
          triggerId: subworkflowTriggerId,
          type: 'subworkflow' as const,
          title: 'Process Text',
          description: 'Called by Main Workflow to process text',
          inputSchema: [{ name: 'text', type: 'string' as const }],
          calledBy: ['main-workflow'],
        } satisfies SubworkflowTrigger,
      ],
      outputSchema: [] as FormOutputSchema,
      n8nWorkflowJsonBase64: textProcessorBase64,
      cost: 0, // Sub-workflows don't cost credits
    },
  ];

  return {
    title: ${JSON.stringify(name)},
    subtitle: ${JSON.stringify(description)},
    description: ${JSON.stringify(description)},
    workflows,
    processDeploymentMarkdown: getProcessMarkdown(),
    tags: ['demo'],
    integrationUids: [],
    icon: ${JSON.stringify(icon)},
  };
}

// ============================================================================
// Schema Definitions
// ============================================================================

function getInputSchema(): FormInputSchema {
  return [
    {
      key: 'text',
      type: 'text',
      label: 'Text',
      description: 'Enter the text to process',
      placeholder: 'Enter text...',
      required: true,
      maxLength: 5000,
      rows: 4,
    },
  ];
}

function getOutputSchema(): FormOutputSchema {
  return [
    {
      key: 'result',
      type: 'text',
      label: 'Result',
      description: 'The processed result',
      required: true,
      rows: 4,
    },
    {
      key: 'processedAt',
      type: 'string',
      label: 'Processed At',
      description: 'Timestamp of processing',
      required: true,
      maxLength: 100,
    },
  ];
}

function getReportOutputSchema(): FormOutputSchema {
  return [
    {
      key: 'title',
      type: 'string',
      label: 'Report Title',
      required: true,
      maxLength: 200,
    },
    {
      key: 'summary',
      type: 'text',
      label: 'Summary',
      required: true,
      rows: 4,
    },
    {
      key: 'generatedAt',
      type: 'string',
      label: 'Generated At',
      required: true,
      maxLength: 100,
    },
  ];
}

// ============================================================================
// Markdown Documentation
// ============================================================================

function getMainWorkflowMarkdown(): string {
  return \`# Main Workflow

## Purpose
Receives text input via HTTP and delegates processing to the text-processor sub-workflow.

## How It Works
1. User submits text via the HTTP trigger
2. Input is validated
3. Text is sent to the text-processor sub-workflow
4. Processed result is returned

## Input
- **Text**: The text to process

## Output
- **Result**: The processed text
- **Processed At**: Timestamp of processing\`;
}

function getScheduledReportMarkdown(): string {
  return \`# Scheduled Report

## Purpose
Generates a report on a recurring schedule (every Monday at 9 AM).

## How It Works
1. Schedule trigger fires automatically
2. Report is generated
3. Result is submitted

## Output
- **Title**: Report title
- **Summary**: Report summary
- **Generated At**: Timestamp\`;
}

function getTextProcessorMarkdown(): string {
  return \`# Text Processor (Sub-Workflow)

## Purpose
Called by the main workflow to process text. Not directly accessible by users.

## How It Works
1. Receives text from the parent workflow
2. Processes the text (uppercase + timestamp)
3. Returns the result to the parent

## Input (from parent)
- **text**: String to process

## Output (to parent)
- **originalText**: The original input
- **processedText**: Processed version
- **processedAt**: ISO timestamp\`;
}

function getProcessMarkdown(): string {
  return \`# ${name.replace(/`/g, "'")}

${description.replace(/`/g, "'")}

## Workflows

### Main Workflow
- **Trigger**: HTTP POST
- **Function**: Receives user input, validates it, and delegates to the text processor sub-workflow

### Scheduled Report
- **Trigger**: Schedule (every Monday at 9 AM)
- **Function**: Generates a periodic report

### Text Processor (Sub-Workflow)
- **Trigger**: Called by Main Workflow (not user-accessible)
- **Function**: Processes text and returns the result

## Getting Started

1. Edit the workflow JSON files in \\\`workflows/\\\` to add your business logic
2. Update the schemas in this file to match your input/output
3. Run: \\\`codika-helper verify use-case .\\\`
4. Run: \\\`codika-helper deploy use-case .\\\`\`;
}
${withDataIngestion ? generateDataIngestionSection(slug) : ''}`;
}

function generateDataIngestionSection(slug: string): string {
  return `
// ============================================================================
// Data Ingestion Configuration (Process-Level)
// ============================================================================

/**
 * Get the data ingestion configuration for this use case.
 *
 * This is deployed separately via:
 *   codika-helper deploy process-data-ingestion <path>
 *
 * The workflow file is auto-discovered from the data-ingestion/ folder.
 */
export function getDataIngestionConfig(): ProcessDataIngestionConfigInput {
  const workflowBase64 = loadAndEncodeWorkflow(
    join(__dirname, 'data-ingestion/${slug}-embedding-ingestion.json')
  );

  return {
    workflowTemplateId: '${slug}-embedding-ingestion',
    workflowName: 'Embedding Ingestion',
    n8nWorkflowJsonBase64: workflowBase64,
    webhooks: {
      embed: \\\`{{PROCDATA_PROCESS_ID_ATADCORP}}/embed\\\`,
      delete: \\\`{{PROCDATA_PROCESS_ID_ATADCORP}}/embed-delete\\\`,
    },
    purpose: 'Embed KB documents into Pinecone for RAG retrieval',
    cost: 2,
  };
}
`;
}
