/**
 * WORKFLOW-SANITIZATION Validation Script
 *
 * Validates that workflows don't contain n8n-generated properties
 * that should be removed before committing:
 * - id
 * - versionId
 * - meta
 * - active
 * - tags
 * - pinData
 *
 * @see .guides/use-case-guide.md - "Properties to Remove" (Section 12)
 */

import type { Finding, RuleMetadata } from '../types.js';

export const RULE_ID = 'WORKFLOW-SANITIZATION';

/**
 * Properties that should be removed from workflow JSON before committing.
 * These are generated by n8n and should not be version-controlled.
 */
export const FORBIDDEN_PROPERTIES = [
  'id',
  'versionId',
  'meta',
  'active',
  'tags',
  'pinData',
] as const;

export const metadata: RuleMetadata & { guideRef: { path: string; section: string } } = {
  id: RULE_ID,
  name: 'workflow_sanitization',
  severity: 'must',
  description: 'Workflows must not contain n8n-generated properties',
  details: `Remove the following properties from workflow JSON: ${FORBIDDEN_PROPERTIES.join(', ')}`,
  fixable: true,
  category: 'sanitization',
  guideRef: {
    path: 'use-case-guide.md',
    section: 'Properties to Remove',
  },
};

/**
 * Validates that workflow doesn't contain forbidden properties
 */
export function checkWorkflowSanitization(content: string, path: string): Finding[] {
  const findings: Finding[] = [];

  // Try to parse JSON
  let workflow: Record<string, unknown>;

  try {
    workflow = JSON.parse(content);
  } catch {
    findings.push({
      rule: RULE_ID,
      severity: 'must',
      path,
      message: 'Cannot parse workflow JSON',
      raw_details: 'Ensure the workflow file contains valid JSON',
      guideRef: metadata.guideRef,
    });
    return findings;
  }

  // Check for each forbidden property
  for (const prop of FORBIDDEN_PROPERTIES) {
    if (prop in workflow) {
      findings.push({
        rule: RULE_ID,
        severity: 'must',
        path,
        message: `Workflow contains forbidden property "${prop}"`,
        raw_details: `Remove the "${prop}" property from the workflow JSON. This is generated by n8n and should not be version-controlled.`,
        guideRef: metadata.guideRef,
        fixable: true,
        fix: {
          description: `Remove "${prop}" property`,
          apply: (content: string) => {
            const wf = JSON.parse(content);
            delete wf[prop];
            return JSON.stringify(wf, null, 2);
          },
        },
      });
    }
  }

  return findings;
}

export default checkWorkflowSanitization;
